### ISSUE TITLE
application crashes in builtin bridge type from dependency package HandyJSON

### ISSUE THREAD

**Issue by tech4solitude** [sacOO7/socketcluster-client-swift#13] opened 2018-07-26 01:27 UTC
Hello @sacOO7 , We're experiencing a couple of crash due to handy JSON. can you please check this  - PFA screen shot of report 
<img width="1140" alt="screenshot 2018-07-26 at 6 55 25 am" src="https://user-images.githubusercontent.com/13044958/43236097-f749d5be-90a0-11e8-9ca6-9e0a8af01978.png">
I've also raised this issues in Handy JSON https://github.com/alibaba/HandyJSON/issues/272

**Comment by sacOO7** [comment] 2018-07-26 06:55
Hi @tech4solitude , will surely look into it 👍 . I am not sure, why it will be causing this issue.... It is a stable library.

**Comment by tech4solitude** [comment] 2018-07-26 06:58
@sacOO7  Thank you - Please update it here - if you find anything

**Comment by sacOO7** [comment] 2018-07-26 07:17
Meanwhile it will be really useful if you can reproduce the issue locally.
In the error log it's saying, that it is something related to empty list.
Can you check it once again?

**Comment by tech4solitude** [comment] 2018-07-27 05:46
@sacOO7  Sure thanks alot - meanwhile I'm also checking to reproduce the crashes

**Comment by tech4solitude** [comment] 2018-07-27 05:47
Also as a suggestion, You could also try SwiftyJSON once which is similar to HandyJSON

**Comment by sacOO7** [comment] 2018-07-27 05:50
Actually I was planning to use SwiftyJson at first. But it does not allow to direct conversion from json to object. User need to write code that specifies mapping. It's not a good way to mention keys everytime a mapping is made. It creates problem while refactoring. In other languages, there are JsonMappers available to map object to json and vice versa. You can check this one https://www.newtonsoft.com/json.

**Comment by tech4solitude** [comment] 2018-07-27 05:53
@sacOO7  Ok got it..  Make sense

**Comment by sacOO7** [comment] 2018-08-02 06:02
Hi @tech4solitude, you were able to get any updates on this?

**Comment by tech4solitude** [comment] 2018-08-02 19:04
@sacOO7  Nope - Tried couple of times - Didn't crash for me - Not sure when it'll crash

**Comment by sacOO7** [comment] 2018-08-17 07:13
Will be closing the issue, if your app is working fine 👍

**Comment by tech4solitude** [comment] 2018-08-23 06:00
It has not crashed after update

**Comment by sacOO7** [comment] 2018-11-12 10:18
Hi @tech4solitude , I will be closing the issue... since there are no updates regarding this...

**Comment by sacOO7** [comment] 2018-11-12 10:19
Please open new issue, if you find any bugs in library

**Closed by sacOO7** 2018-11-12 10:19 UTC
